version: '3.4'

services:
  postgres:
    image: postgres:15.2-alpine
    restart: on_failure
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    ports:
      - 5432:5432

